[package]
name = "password-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
base64 = "0.22.1"
hex = "0.4.3"
password-hash = "0.5.0"
rand = "0.8"
serde = {version = "1.0.228", features=["derive"]}
serde_json = "1.0.145"
